<a href="https://colab.research.google.com/github/madhav7034/Notes/blob/main/Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Numpy used for arrays
NUMerical PYthon (Numpy)
Open source
Applications of Machine learning and deep learning



import numpy as np

1. Array

Collection of elements one or more dimensions
1 D array is called vector, 2D array is called matrix
numpy arrays contains only homoge elements= more efficient


python list most suitable for data storage

Numpy applied in:
Data manipulation and analysis
Scientific

"""
import numpy as np
x = np.array([12,14,23,45])
x


array([12, 14, 23, 45])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape

(5,)

In [ ]:
x.ndim

1

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([
    [1,2,3],
    [7,8,9],
    [5,6,4],
])
y

array([[1, 2, 3],
       [7, 8, 9],
       [5, 6, 4]])

In [ ]:
y.shape

(3, 3)

In [ ]:
y.size

9

In [ ]:
xy =  np.array([1,3.5,7,6.8],dtype=np.int64)
xy

array([1, 3, 7, 6])

In [ ]:
xy + 3

array([ 4,  6, 10,  9])

In [ ]:
xy / 2

array([0.5, 1.5, 3.5, 3. ])

In [ ]:
xy * 5

array([ 5, 15, 35, 30])

In [ ]:
i = np.zeros((3,4),dtype=np.int64)
i

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
q = np.ones((3,4),dtype=np.int64)
q

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
w = np.eye(4)
w

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
e = np.diag([100,21,-12,15])
e

array([[100,   0,   0,   0],
       [  0,  21,   0,   0],
       [  0,   0, -12,   0],
       [  0,   0,   0,  15]])

In [ ]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t = np.arange(1,10,2)
t

array([1, 3, 5, 7, 9])

In [ ]:
t.size

5

In [ ]:
len(t)

5

In [ ]:
t.shape

(5,)

In [ ]:
u = np.reshape(t,(5,1))
u

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
import random
A = np.random.random([4,5])
A

array([[3.82711856e-01, 9.62457054e-01, 5.26124898e-01, 9.18122868e-01,
        3.67337522e-01],
       [3.45119743e-04, 9.12896537e-01, 3.13513245e-02, 8.74286512e-01,
        3.26116369e-01],
       [2.40343470e-01, 4.96684898e-01, 6.55348306e-03, 7.30645534e-01,
        1.48984502e-01],
       [9.00132146e-01, 6.78595153e-01, 7.36615555e-01, 6.76223511e-01,
        2.80316983e-01]])

In [ ]:
B = np.random.randint(3,34,size=(3,4))
B

array([[ 8,  9, 30,  8],
       [17, 24,  7, 30],
       [10, 17, 27, 23]])

In [ ]:
B[0]

array([ 8,  9, 30,  8])

In [ ]:
B[-1]

array([10, 17, 27, 23])

In [ ]:
B[0:2]

array([[ 8,  9, 30,  8],
       [17, 24,  7, 30]])

In [ ]:
B[0,0]

np.int64(8)

In [ ]:
B[-1,-1]

np.int64(23)

In [ ]:
B[1:3]

array([[17, 24,  7, 30],
       [10, 17, 27, 23]])

In [ ]:
B[1:,2:]

array([[ 7, 30],
       [27, 23]])

In [ ]:
"""
transpose
pull
index pos max value
dot func
power
where
percentile
cumulative
std dev
arg
copy
view

"""
#Sort

q1 = [7,3,8,15,11,2]
q2 = np.sort(q1)
q2

array([ 2,  3,  7,  8, 11, 15])

In [ ]:
#Count non zero numbers
q1 = [10,20,0,56,34,0,23,123,0]
q2 = np.count_nonzero(q1)
q2

6

In [ ]:
#Add matrix

x = np.array([
    [1,2,4],
    [5,6,7],
    [1,1,1],
])

y = np.array([
    [1,2,4],
    [5,6,7],
    [1,1,1],
])
xy = np.add(x,y)
xy

array([[ 2,  4,  8],
       [10, 12, 14],
       [ 2,  2,  2]])

In [ ]:
#Sub
x = np.array([
    [8,3,10],
    [5,6,7],
    [1,1,1],
])

y = np.array([
    [1,2,4],
    [11,62,2],
    [5,4,2],
])
xy = np.subtract(x,y)
xy

array([[  7,   1,   6],
       [ -6, -56,   5],
       [ -4,  -3,  -1]])

In [ ]:
#Mean
q2 = [2,3,4,5,6]
q3 = np.mean(q2)
q3

np.float64(4.0)

In [ ]:
#Median
q3 = np.median(q2)
q3

np.float64(4.0)

In [ ]:
#Add array
x = [1,3,4,5]
y = [3,6,7,8]
z = np.add(x,y)
z

array([ 4,  9, 11, 13])

In [ ]:
"""
Pandas

data from diff resources can be loaded
Easy handling of missing data
Data set merging and joining
Analyse big data
Clean messy datasets

import panda as pd
Open source built on top of NumPy
"""

import pandas as pd
s = pd.Series([1,2,3,4,np.nan,6,7])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
dtype: float64

In [ ]:
df = pd.DataFrame(np.random.randint(0,100,size=(5,3)),columns=['A','B','C'])
df

A   B   C
0  74  51  89
1  41  29  17
2  95  32  74
3  53  71  32
4   2  19  98

In [ ]:
data = {
    'Calories':[400,350,300,410,500,530,500],
    'Duration':[10,20,30,40,50,60,70]
}
d = pd.DataFrame(data)
print(d)

   Calories  Duration
0       400        10
1       350        20
2       300        30
3       410        40
4       500        50
5       530        60
6       500        70


In [ ]:
d['Calories']

0    400
1    350
2    300
3    410
4    500
5    530
6    500
Name: Calories, dtype: int64

In [ ]:
d.loc[1]

Calories    350
Duration     20
Name: 1, dtype: int64

In [ ]:
d.loc[0:5]

Calories  Duration
0       400        10
1       350        20
2       300        30
3       410        40
4       500        50
5       530        60

In [ ]:
data = {
    'Calories':[400,350,300,410,500,530,500],
    'Duration':[10,20,30,40,50,60,70]
}
d = pd.DataFrame(data,index=['day1','day2','day3','day4','day5','day6','day7'])
print(d)

      Calories  Duration
day1       400        10
day2       350        20
day3       300        30
day4       410        40
day5       500        50
day6       530        60
day7       500        70


In [ ]:
d



Calories  Duration
day1       400        10
day2       350        20
day3       300        30
day4       410        40
day5       500        50
day6       530        60
day7       500        70

In [ ]:
d.iloc[0:5]

Calories  Duration
day1       400        10
day2       350        20
day3       300        30
day4       410        40
day5       500        50

In [ ]:
d.loc['day1':'day3']

Calories  Duration
day1       400        10
day2       350        20
day3       300        30

In [ ]:
d.reset_index(drop=True)

Calories  Duration
0       400        10
1       350        20
2       300        30
3       410        40
4       500        50
5       530        60
6       500        70

In [ ]:
d = pd.read_excel('/content/data.xlsx')

In [ ]:
d.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
d.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
d.shape

(169, 4)

In [ ]:
d.size

676

In [ ]:
d.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
d.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
d.isna()

Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [ ]:
d.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
d[d['Calories']<=100]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
93         15     80       100      50.5
100        20     95       112      77.7
104        30     92       108      92.7
107        30     90       120      86.2

In [ ]:
d[(d['Calories']<=100) & (d['Duration']==20)]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
100        20     95       112      77.7

In [ ]:
d.drop(165)

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
163        45    100       140     280.9
164        60    105       140     290.8
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[168 rows x 4 columns]

In [ ]:
d.drop(['Calories'],axis=1)

Duration  Pulse  Maxpulse
0          60    110       130
1          60    117       145
2          60    103       135
3          45    109       175
4          45    117       148
..        ...    ...       ...
164        60    105       140
165        60    110       145
166        60    115       145
167        75    120       150
168        75    125       150

[169 rows x 3 columns]

In [ ]:
d.nunique()

Duration     16
Pulse        47
Maxpulse     57
Calories    142
dtype: int64

In [ ]:
d['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
d['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
d.groupby('Duration')['Calories'].mean()

Duration
15       87.350000
20      151.600000
25      244.200000
30      192.125000
45      273.236364
60      339.675000
75      325.400000
80      643.100000
90      541.800000
120     666.833333
150     939.400000
160     943.700000
180     733.600000
210    1618.200000
270    1729.000000
300    1500.200000
Name: Calories, dtype: float64

In [ ]:
d["Cal burned"] = d['Calories']/d['Duration']
d.head()

Duration  Pulse  Maxpulse  Calories  Cal burned
0        60    110       130     409.1    6.818333
1        60    117       145     479.0    7.983333
2        60    103       135     340.0    5.666667
3        45    109       175     282.4    6.275556
4        45    117       148     406.0    9.022222

In [ ]:
import seaborn as sns
data = sns.load_dataset('titanic')

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']